import { describe, expect, it } from "vitest";
import type { ProviderAdapterDraft } from "./types";
import { adapterRevisionDigest, validateProviderAdapterDraft } from "./validator";

const baseDraft = (): ProviderAdapterDraft => ({
  provider: {
    baseUrl: "https://api.example.com/v1",
    authType: "bearer",
  },
  sources: [
    {
      url: "https://docs.example.com/api/images",
      title: "Images API",
      evidence: "POST /v1/images/generations accepts model and prompt.",
    },
  ],
  models: [
    {
      modelKey: "paint-v2",
      labelZh: "Paint V2",
      kind: "image",
      modes: [
        {
          taskKind: "text_to_image",
          create: {
            method: "POST",
            path: "/images/generations",
            body: {
              model: "{{model.modelKey}}",
              prompt: "{{request.prompt}}",
              size: "{{request.params.size}}",
            },
            response_mapping: { image_url: "data.0.url" },
          },
          testParams: { size: "1024x1024" },
          sourceUrls: ["https://docs.example.com/api/images"],
        },
      ],
    },
  ],
});

describe("validateProviderAdapterDraft", () => {
  it("accepts a declarative same-origin adapter for a selected model", () => {
    const result = validateProviderAdapterDraft(baseDraft(), {
      providerBaseUrl: "https://api.example.com/v1",
      selectedModelKeys: ["paint-v2"],
    });

    expect(result.models[0]?.modes[0]?.create.method).toBe("POST");
  });

  it("rejects an absolute operation URL on another origin", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].create.path = "https://attacker.invalid/steal";

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/same origin/i);
  });

  it("rejects relative traversal paths", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].create.path = "/images/../admin";

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/traversal/i);
  });

  it("rejects executable transforms generated by the model", () => {
    const draft = baseDraft();
    (draft.models[0].modes[0].create as unknown as Record<string, unknown>).request_transform = "eval-js";

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/request_transform/i);
  });

  it("rejects template roots outside the allowlist", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].create.body = { key: "{{process.env.SECRET}}" };

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/template root/i);
  });

  it("rejects prototype-chain access even when the template root is allowed", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].create.body = { key: "{{request.constructor.constructor}}" };

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/template path/i);
  });

  it("rejects prototype-polluting object keys from generated JSON", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].create.body = JSON.parse('{"constructor":{"prototype":{"polluted":true}}}');

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/object key/i);
  });

  it("rejects a model that the user did not select", () => {
    const draft = baseDraft();
    draft.models.push({
      ...draft.models[0],
      modelKey: "surprise-model",
      modes: [...draft.models[0].modes],
    });

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/not selected/i);
  });

  it("rejects an adapter that silently omits a selected model", () => {
    expect(() =>
      validateProviderAdapterDraft(baseDraft(), {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2", "video-v3"],
      }),
    ).toThrow(/missing selected model/i);
  });

  it("requires an explicit reference parameter for reference-image modes", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].taskKind = "image_edit";

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/referenceParam/i);
  });

  it("requires the reference value shape so the runtime cannot guess between one URL and an array", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].taskKind = "image_edit";
    draft.models[0].modes[0].referenceParam = "referenceImages";

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/referenceShape/i);
  });

  it("requires a media result mapping on either create or query", () => {
    const draft = baseDraft();
    delete draft.models[0].modes[0].create.response_mapping;

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/media result mapping/i);
  });

  it("rejects mode evidence URLs that were not included in the discovered official sources", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].sourceUrls = ["https://untrusted.invalid/fake-docs"];

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/source url/i);
  });

  it("rejects response mapping keys the runtime cannot consume", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].create.response_mapping = { outputUrl: "data.0.url" };

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/response mapping key/i);
  });

  it("rejects prototype-chain response paths", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].create.response_mapping = { image_url: "data.constructor.prototype.url" };

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/response path/i);
  });

  it("rejects task kinds that do not match the billing model kind", () => {
    const draft = baseDraft();
    draft.models[0].kind = "text";

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/model kind/i);
  });
});

describe("adapterRevisionDigest", () => {
  it("is stable across object key insertion order", () => {
    const left = baseDraft();
    const right = baseDraft();
    right.models[0].modes[0].testParams = { quality: "high", size: "1024x1024" };
    left.models[0].modes[0].testParams = { size: "1024x1024", quality: "high" };

    expect(adapterRevisionDigest(left)).toBe(adapterRevisionDigest(right));
  });
});
