// 把档案(src/config/modelArchetypes)的参数默认值抽成纯数据，桥接给 electron。
// 为什么要它：electron/tsconfig rootDir 隔离，runtime 不能直接 import src/config 的档案；
// 但 headless/MCP 生成不经 UI → request.params 为空 → 缺必填参(model 变体 / duration / 比例…) vendor 拒。
// 本脚本(跑在 electron 编译外、可 import src/config)抽 {archetypeId: {taskKind: {param: defaultValue}}}，
// 写成 electron/catalog/archetypeWireDefaults.generated.ts；runtime 按 (archetypeId, taskKind) 兜底填，既有值优先。
// 单一真相源仍是档案：改档案默认 → `pnpm gen:archetype-defaults` 重生成；check:archetype-defaults 门防漂移。
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { MODEL_ARCHETYPES } from "../src/config/modelArchetypes/index.ts";

type WireDefaults = Record<string, Record<string, Record<string, Record<string, unknown>>>>;

// 结构：{ archetypeId: { taskKind: { "*"|vendorKey: { param: default } } } }。
// 同一档案同一 taskKind 在不同 vendor 下参数枚举不同（vendorParams，B 分层，如 apimart Kling duration=number
// vs kie=string "5"）→ 必须按 vendor 分桶，否则会把 kie 的字符串默认喂给 apimart 触发「string≠int」。
// runtime 取 perKind[vendorKey] ?? perKind["*"]。
export function buildArchetypeWireDefaults(): WireDefaults {
  const out: WireDefaults = {};
  for (const arch of MODEL_ARCHETYPES) {
    const defaultVariant =
      arch.variants && arch.defaultVariantId ? arch.variants.find((v) => v.id === arch.defaultVariantId) : undefined;
    for (const mode of arch.modes) {
      const taskKind = mode.transportTaskKind ?? arch.transportTaskKind;
      if (!taskKind) continue;
      // body 的 model 字段：mode.modelEnum 优先，否则档案默认变体的 modelKey（headless 不选变体=默认变体）。
      const model = mode.modelEnum ?? defaultVariant?.modelKey;
      // 通用 params 落 "*"；每个有 vendorParams 覆盖的 vendor 落各自桶（覆盖=整组替换，与 resolveArchetypeForModel 一致）。
      const paramSets: Record<string, typeof mode.params> = { "*": mode.params ?? [], ...(mode.vendorParams ?? {}) };
      for (const [vendorKey, params] of Object.entries(paramSets)) {
        const d: Record<string, unknown> = {};
        // 模式级固定 body 常量（如 Veo/Omni 的 generation_type）——headless 也必发，各 vendor 桶都带。
        for (const [k, v] of Object.entries(mode.fixedParams ?? {})) d[k] = v;
        // 用户可调参的默认值（duration=number 保类型，避 vendor「string≠int」）。
        for (const p of params ?? []) {
          if (typeof p.defaultValue !== "undefined") d[p.key] = p.defaultValue;
        }
        if (model) d.model = model;
        if (Object.keys(d).length === 0) continue;
        out[arch.id] = out[arch.id] ?? {};
        out[arch.id][taskKind] = out[arch.id][taskKind] ?? {};
        (out[arch.id][taskKind] as Record<string, Record<string, unknown>>)[vendorKey] = d;
      }
    }
  }
  return out;
}

/**
 * 档案身份表：{ archetypeId: identifierPatterns[] }。
 * 为什么也要桥过去：主进程要能从 modelKey 认出档案（中转接入时决定「这个模型有没有可复用的
 * 原生报文」、启动自愈时同理），而档案住 src/config、electron 直接 import 不到。匹配规则与
 * resolveArchetypeForModel 同源（整串相等 或 去掉 vendor 前缀后的末段相等），实现在
 * electron/catalog/archetypeIdentity.ts。
 */
export function buildArchetypeIdentifierPatterns(): Record<string, string[]> {
  const out: Record<string, string[]> = {};
  for (const arch of MODEL_ARCHETYPES) {
    const patterns = [...(arch.identifierPatterns ?? [])];
    // 变体 modelKey 也是这个档案的身份（用户接入的可能是 fast/mini 那一支）。
    for (const v of arch.variants ?? []) if (v.modelKey) patterns.push(v.modelKey);
    const unique = [...new Set(patterns.map((p) => String(p).trim()).filter(Boolean))];
    if (unique.length) out[arch.id] = unique;
  }
  return out;
}

const BANNER = "// @generated by scripts/gen-archetype-wire-defaults.ts — 请勿手改（改档案后跑 pnpm gen:archetype-defaults）。\n";

export function renderGeneratedFile(defaults: WireDefaults): string {
  return (
    `${BANNER}// 档案参数默认值桥接：headless/MCP 生成缺参时 runtime 按 (archetypeId, taskKind) 兜底填，既有值优先。\n` +
    `export const ARCHETYPE_WIRE_DEFAULTS: Record<string, Record<string, Record<string, Record<string, unknown>>>> = ${JSON.stringify(defaults, null, 2)};\n`
  );
}

/** 身份表单独一个文件：与默认值是两件事（一个给 headless 兜底、一个给主进程认档案），
 *  合在一起还会把生成文件顶过 800 行的巨壳门岗。 */
export function renderIdentifiersFile(identifiers: Record<string, string[]>): string {
  return (
    `${BANNER}// 档案身份桥接：主进程从 modelKey 认出档案（中转接入选原生报文用）；匹配实现在 archetypeIdentity.ts。\n` +
    `export const ARCHETYPE_IDENTIFIER_PATTERNS: Record<string, string[]> = ${JSON.stringify(identifiers, null, 2)};\n`
  );
}

const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  const dir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../electron/catalog");
  const outputs: Array<{ file: string; content: string }> = [
    { file: "archetypeWireDefaults.generated.ts", content: renderGeneratedFile(buildArchetypeWireDefaults()) },
    { file: "archetypeIdentifiers.generated.ts", content: renderIdentifiersFile(buildArchetypeIdentifierPatterns()) },
  ];
  if (process.argv.includes("--check")) {
    for (const { file, content } of outputs) {
      const target = path.join(dir, file);
      const existing = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : "";
      if (existing !== content) {
        console.error(`✗ ${file} 与档案不同步——跑 \`pnpm gen:archetype-defaults\` 重生成后提交。`);
        process.exit(1);
      }
    }
    console.log("✓ 档案默认参数桥接已同步。");
  } else {
    for (const { file, content } of outputs) fs.writeFileSync(path.join(dir, file), content);
    console.log(`wrote ${outputs.map((o) => o.file).join(", ")} (${Object.keys(buildArchetypeWireDefaults()).length} archetypes)`);
  }
}
